version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: Supabase local stack (if not using cloud)
  # Uncomment if you want to run Supabase locally
  # supabase:
  #   image: supabase/supabase-local
  #   ports:
  #     - "54321:54321"  # Studio
  #     - "54322:54322"  # API Gateway
  #     - "54323:54323"  # DB
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - supabase_data:/var/lib/postgresql/data

volumes:
  redis_data:
  # supabase_data:  # Uncomment if using local Supabase

networks:
  default:
    name: lottery-admin-network